[project]
name = "sample-app"
version = "0.1.0"
description = "sample app"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "google-genai>=1.62.0",
]

[dependency-groups]
dev = [
    "ruff>=0.15.0",
    "ty>=0.0.15",
]
